# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UberRider' do
  use_frameworks!
  
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'ObjectMapper', '~> 2.2'
  pod 'JSQMessagesViewController'
end
